"""
Fine-tune GLiNER2 on synthetic German ward handover data via LoRA.

Run from backend/ directory:
    .venv/bin/python scripts/finetune.py

Requires:
  - data/training/train.jsonl  (generated by generate_training_data.py)
  - data/training/eval.jsonl

Output:
  - models/lora_handover/  (LoRA adapter, ~few MB)
"""

from __future__ import annotations

import logging
import os
import sys
from pathlib import Path

# Ensure backend/ is in path so relative HF_HOME resolution works
BASE_DIR = Path(__file__).parent.parent.resolve()

# Set HF cache before any HF imports
os.environ.setdefault("HF_HOME", str(BASE_DIR / ".hf_cache"))

logging.basicConfig(
    format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
    level=logging.INFO,
)
logger = logging.getLogger("finetune")


def main() -> None:
    train_path = BASE_DIR / "data" / "training" / "train.jsonl"
    eval_path = BASE_DIR / "data" / "training" / "eval.jsonl"
    adapter_dir = BASE_DIR / "models" / "lora_handover"

    for p in (train_path, eval_path):
        if not p.exists():
            sys.exit(
                f"Missing {p}. "
                "Run scripts/generate_training_data.py first."
            )

    # Count examples
    with open(train_path) as f:
        n_train = sum(1 for _ in f)
    with open(eval_path) as f:
        n_eval = sum(1 for _ in f)
    logger.info("Training on %d examples, eval on %d examples", n_train, n_eval)

    logger.info("Loading base model fastino/gliner2-base-v1 ...")
    from gliner2 import GLiNER2

    model = GLiNER2.from_pretrained("fastino/gliner2-base-v1")
    logger.info("Model loaded.")

    from gliner2.training.trainer import TrainingConfig, GLiNER2Trainer

    config = TrainingConfig(
        output_dir=str(adapter_dir),
        experiment_name="handover_lora",
        num_epochs=3,
        batch_size=2,
        gradient_accumulation_steps=4,   # effective batch size = 8
        encoder_lr=1e-5,
        task_lr=5e-5,
        use_lora=True,
        lora_r=8,
        lora_alpha=16.0,
        lora_target_modules=["encoder"],
        save_adapter_only=True,
        fp16=False,   # no GPU
        bf16=False,
        eval_strategy="epoch",
        save_total_limit=1,
        report_to_wandb=False,
    )

    trainer = GLiNER2Trainer(model, config)
    logger.info("Starting training (CPU, LoRA r=8) ...")
    trainer.train(
        train_data=str(train_path),
        eval_data=str(eval_path),
    )

    logger.info("Training complete. Adapter saved to %s", adapter_dir)


if __name__ == "__main__":
    main()
